In [7]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [11]:
def prepare_seq(notes, sequence_length):
    network_input = []
    network_output = []

    for i in range(0, len(notes) - sequence_length, 1):
        sequence_in = notes[i:i + sequence_length]
        sequence_out = notes[i + sequence_length]
        network_input.append(sequence_in)
        network_output.append(sequence_out)

    return np.array(network_input), np.array(network_output)


def create_dataset(dataset, look_back=1):
    dataX, dataY = [], []
    for i in range(len(dataset) - look_back - 1):
        a = dataset[i:(i + look_back), 0]
        dataX.append(a)
        dataY.append(dataset[i + look_back, 0])
    return np.array(dataX), np.array(dataY)

In [16]:
data = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [17]:
scaler = MinMaxScaler(feature_range=(0, 1))
data = data.reshape(-1, 1)


In [21]:
x, y = prepare_seq(data, 3)

In [22]:
x

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 2],
        [ 3],
        [ 4]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 7],
        [ 8],
        [ 9]],

       [[ 8],
        [ 9],
        [10]],

       [[ 9],
        [10],
        [11]]])

In [18]:
x,y = create_dataset(data, 3)

In [19]:
x

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10]])

In [20]:
y

array([ 4,  5,  6,  7,  8,  9, 10, 11])